name: Deploy Cloud Function

on:
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - 'requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_DEPLOY_KEY }}
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'


    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy func2 \
        --gen2 \
        --region=us-east1 \
        --runtime=python38 \
        --entry-point=main \
        --memory=256Mi \
        --trigger-http
