name: Deploy Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: fantasy-transfer-monitor 
        export_default_credentials: true

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy func2 \
        --gen2 \
        --region=us-east1 \
        --runtime=python38 \
        --entry-point=main \
        --memory=128Mi \
        --trigger-http