name: Deploy Cloud Function

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    = name: Deploy Cloud Function
      run: |
        gcloud functions deploy func-2 \
          --gen2 \ 
          --runtime python38 \
          --entry-point main \
