name: Invoke Cloud Function

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  invoke:
    runs-on: ubuntu-latest
    
    steps:
  
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_DEPLOY_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: 'Invoke Cloud Function'
      run: |
        curl -m 70 -X POST https://us-east1-fantasy-transfer-monitor.cloudfunctions.net/func2 \ 
          -H "Authorization: bearer $(gcloud auth print-identity-token)" \
          -H "Content-Type: application/json" \
          -d '{}'